---
- name: Install required Ansible collections
  hosts: localhost
  connection: local
  tasks:
    - name: Install community.docker collection
      ansible.builtin.command: ansible-galaxy collection install community.docker
      changed_when: false
