---
- name: Teardown Development Environment
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Set ansible_user if not defined
      ansible.builtin.set_fact:
        ansible_user: "{{ lookup('env', 'USER') }}"
      when: ansible_user is not defined
      tags:
        - always

  roles:
    - role: teardown_motor_ingestion
    - role: teardown_grafana
    - role: teardown_influxdb
    - role: teardown_udev_user

  tasks:
    - name: Stop all running Docker containers (including orphans)
      become: true
      ansible.builtin.shell: |
        docker ps -q | xargs -r docker stop
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Remove all Docker containers (including stopped)
      become: true
      ansible.builtin.shell: |
        docker ps -a -q | xargs -r docker rm -f
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Remove Docker images (explicit list)
      become: true
      community.docker.docker_image:
        name: "{{ item }}"
        state: absent
        force_absent: true
      loop:
        - influxdb:3.7.0-core
        - grafana/grafana:main
        - python:3.14-slim
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Remove dangling Docker images
      become: true
      ansible.builtin.shell: |
        docker image prune -a -f
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Remove Docker volumes (if any orphaned)
      become: true
      ansible.builtin.shell: |
        docker volume prune -f
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Remove Docker network
      become: true
      community.docker.docker_network:
        name: m-network
        state: absent
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Get current user groups
      ansible.builtin.command: id -G -n {{ ansible_user }}
      register: user_groups
      changed_when: false
      tags:
        - teardown_docker

    - name: Remove ansible_user from the docker group (preserve other groups)
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "{{ user_groups.stdout.split() | difference(['docker']) | join(',') }}"
        append: false
      when: "'docker' in user_groups.stdout.split()"
      tags:
        - teardown_docker

    - name: Get udev1 user groups
      ansible.builtin.command: id -G -n udev1
      register: udev_groups
      changed_when: false
      failed_when: false
      tags:
        - teardown_docker

    - name: Remove udev1 from the docker group (preserve other groups)
      become: true
      ansible.builtin.user:
        name: "udev1"
        groups: "{{ udev_groups.stdout.split() | difference(['docker']) | join(',') }}"
        append: false
      when: 
        - udev_groups.rc == 0
        - "'docker' in udev_groups.stdout.split()"
      tags:
        - teardown_docker

    - name: Stop and disable Docker service
      become: true
      ansible.builtin.systemd:
        name: docker
        state: stopped
        enabled: false
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Stop containerd service if running
      become: true
      ansible.builtin.systemd:
        name: containerd
        state: stopped
        enabled: false
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Uninstall Docker packages
      become: true
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-ce-rootless-extras
          - docker-compose
        state: absent
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Remove Docker service and socket files
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/docker.service
        - /etc/systemd/system/docker.socket
        - /etc/systemd/system/containerd.service
        - /etc/docker
        - /var/lib/docker
        - /var/lib/containerd
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Clean up Docker installer script
      become: true
      ansible.builtin.file:
        path: /tmp/get-docker.sh
        state: absent
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Reload systemd daemon to clean up Docker services
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
      ignore_errors: true
      tags:
        - teardown_docker

    - name: Display teardown completion information
      ansible.builtin.debug:
        msg:
          - "========================================="
          - "  Teardown Complete!"
          - "========================================="
          - ""
          - "COMPLETELY REMOVED:"
          - "  - All Docker containers (running and stopped)"
          - "  - All Docker images (including orphans)"
          - "  - Motor Ingestion Python image"
          - "  - Docker network (m-network)"
          - "  - Docker group membership"
          - "  - Docker daemon and containerd services"
          - "  - Docker packages (docker-ce, containerd, plugins)"
          - "  - Docker configuration files (/etc/docker)"
          - "  - Docker storage (/var/lib/docker, /var/lib/containerd)"
          - "  - Docker installer script (/tmp/get-docker.sh)"
          - ""
          - "PRESERVED (for recovery/audit):"
          - "  - /home/udev1/ directory with all data"
          - "  - InfluxDB data: /home/udev1/influxdb-data/"
          - "  - Grafana data: /home/udev1/grafana-data/"
          - "  - Motor ingestion: /home/udev1/motor_ingestion/"
          - ""
          - "To manually delete all preserved data:"
          - "  rm -rf /home/udev1/"
          - ""
          - "Or delete selectively:"
          - "  rm -rf /home/udev1/influxdb-data"
          - "  rm -rf /home/udev1/grafana-data"
          - "  rm -rf /home/udev1/motor_ingestion"
          - ""
          - "NOTE: You may need to log out and back in for Docker group"
          - "      changes to take effect. Docker is completely uninstalled."
          - "========================================="
      tags:
        - always
